name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4
      - name: Lint (strict)
        run: swiftlint lint --strict .
